apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: baby-blockchain-1
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: tmp
                mountPath: /tmp
        volumes:
          - name: tmp
            emptyDir: {}
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: us.gcr.io/idekctf-374221/baby-blockchain-1-healthcheck:4950ce0c06c00436344f7e5c292bc59cac43990394f125dc15e69a13c3318eac
  image: us.gcr.io/idekctf-374221/baby-blockchain-1-challenge:94a4db86700197c499d1e641d7584ab0a819895d3883a4021bb635b8f6ffc705
