apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: malbolge3
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: us.gcr.io/idekctf-374221/malbolge3-healthcheck:478290d81167dfdc5c1529030e7a1c49c91c4d1a25f01ab39c0cbba68ae03547
  image: us.gcr.io/idekctf-374221/malbolge3-challenge:aa35b9ce365c453981efda07bfad6c79de97888a7206eacbb5527a8301253071
