apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: paywall
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 1337
        targetPort: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: run
                mountPath: /var/run/apache2
        volumes:
          - name: run
            emptyDir: {}
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: us.gcr.io/idekctf-374221/paywall-healthcheck:80cf6fac94d4ac44019c14997b83302326521dd2a2aff67c60a8777c12b48c09
  image: us.gcr.io/idekctf-374221/paywall-challenge:48b0de4bf85b6358e26320d5da6fb62dd8db868e465928001577de60208981e0
